# Generated by Django 4.1.3 on 2022-12-04 07:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_loginuser_age_loginuser_birth_day_loginuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='avatars'),
        ),
    ]
