# Generated by Django 4.1.3 on 2022-12-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_loginuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='profile_image',
        ),
    ]
